/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainGUI.java
 *
 * Created on Mar 15, 2012, 7:09:49 PM
 */
package ps;

import Library.PacketStat;
import Library.PSCaptor;
import java.io.File;
import javamodules.FilterSetting;
import javamodules.LogFileBrowse;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import sun.rmi.log.ReliableLog.LogFile;

/**
 *
 * @author RAVI
 */
public class MainGUI extends javax.swing.JFrame {

    public DefaultTableModel dtmPacket = new DefaultTableModel();
    PSCaptor ps;
    /** Creates new form MainGUI */
    public MainGUI(int bufsize,boolean mode,int deviceno) {
        initComponents();
        /*BasicConfiguration bc = new BasicConfiguration();
        bc.setLocationByPlatform(true);
        bc.setVisible(true);
        bc.setAlwaysOnTop(true);*/
        deletePreviousFiles();
        packetbtn.setSelected(true);
        packetView.setVisible(true);
        sessionView.setVisible(false);
        packetTable.setCellSelectionEnabled(false);
        packetTable.setRowSelectionAllowed(true);
        packetTable.setColumnSelectionAllowed(false);
        packetTable.setShowGrid(false);
        packetTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        stopPacketbtn();
        refreshbtn.setEnabled(false);
        dtmPacket = (DefaultTableModel)packetTable.getModel();
        sessionArea.setEditable(false);
        packetArea.setEditable(false);
        packetTable.getColumnModel().getColumn(11).setMaxWidth(0);
        packetTable.getColumnModel().getColumn(11).setMinWidth(0);
        packetTable.getColumnModel().getColumn(11).setPreferredWidth(0);
        ps = new PSCaptor(deviceno,mode, bufsize,dtmPacket , sessionArea);
        
    }

    private MainGUI() {
        
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        packetView = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        packetArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        packetTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        sessionView = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        sessionArea = new javax.swing.JTextArea();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        packetPanel = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        sessionPanel = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        refreshbtn = new javax.swing.JButton();
        startbtn = new javax.swing.JButton();
        stopbtn = new javax.swing.JButton();
        packetbtn = new javax.swing.JButton();
        sessionbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KEC IDS");
        setMinimumSize(new java.awt.Dimension(1250, 750));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        packetView.setBackground(new java.awt.Color(51, 0, 204));
        packetView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        packetView.setMaximumSize(new java.awt.Dimension(1100, 630));
        packetView.setMinimumSize(new java.awt.Dimension(1100, 630));
        packetView.setPreferredSize(new java.awt.Dimension(1100, 630));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("     Packet Content");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        packetArea.setColumns(20);
        packetArea.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        packetArea.setRows(5);
        jScrollPane1.setViewportView(packetArea);

        packetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr. No.", "Time", "MAC Source", "MAC Destination", "Frame", "Protocol", "IP Source", "IP Destination", "Port Source", "Port Destination", "Size", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        packetTable.setColumnSelectionAllowed(true);
        packetTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                packetTableMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(packetTable);
        packetTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("     Packet View");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout packetViewLayout = new javax.swing.GroupLayout(packetView);
        packetView.setLayout(packetViewLayout);
        packetViewLayout.setHorizontalGroup(
            packetViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1111, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1111, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1111, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1111, Short.MAX_VALUE)
        );
        packetViewLayout.setVerticalGroup(
            packetViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(packetViewLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );

        packetView.setBounds(0, 0, 1115, 630);
        jDesktopPane1.add(packetView, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sessionView.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        sessionView.setEnabled(false);
        sessionView.setMaximumSize(new java.awt.Dimension(1100, 630));
        sessionView.setMinimumSize(new java.awt.Dimension(1100, 630));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 15)); // NOI18N
        jLabel3.setText("     Session View");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));

        sessionArea.setColumns(20);
        sessionArea.setRows(5);
        jScrollPane3.setViewportView(sessionArea);

        javax.swing.GroupLayout sessionViewLayout = new javax.swing.GroupLayout(sessionView);
        sessionView.setLayout(sessionViewLayout);
        sessionViewLayout.setHorizontalGroup(
            sessionViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1111, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1111, Short.MAX_VALUE)
        );
        sessionViewLayout.setVerticalGroup(
            sessionViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sessionViewLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
        );

        sessionView.setBounds(0, 0, 1115, 630);
        jDesktopPane1.add(sessionView, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 70, 1115, 630));

        packetPanel.setBackground(new java.awt.Color(0, 0, 204));

        jToolBar2.setBackground(new java.awt.Color(0, 0, 204));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        javax.swing.GroupLayout packetPanelLayout = new javax.swing.GroupLayout(packetPanel);
        packetPanel.setLayout(packetPanelLayout);
        packetPanelLayout.setHorizontalGroup(
            packetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(packetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        packetPanelLayout.setVerticalGroup(
            packetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, packetPanelLayout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        packetPanel.setBounds(0, 0, 130, 60);
        jDesktopPane2.add(packetPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jToolBar3.setFloatable(false);
        jToolBar3.setRollover(true);

        refreshbtn.setText("REFRESH");
        refreshbtn.setFocusable(false);
        refreshbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refreshbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtnActionPerformed(evt);
            }
        });
        jToolBar3.add(refreshbtn);

        javax.swing.GroupLayout sessionPanelLayout = new javax.swing.GroupLayout(sessionPanel);
        sessionPanel.setLayout(sessionPanelLayout);
        sessionPanelLayout.setHorizontalGroup(
            sessionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(sessionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );
        sessionPanelLayout.setVerticalGroup(
            sessionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(sessionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );

        sessionPanel.setBounds(0, 0, 130, 60);
        jDesktopPane2.add(sessionPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1146, 0, 120, 60));

        startbtn.setText("START");
        startbtn.setFocusable(false);
        startbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        startbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        startbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbtnActionPerformed(evt);
            }
        });
        getContentPane().add(startbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        stopbtn.setText("STOP");
        stopbtn.setFocusable(false);
        stopbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stopbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        stopbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopbtnActionPerformed(evt);
            }
        });
        getContentPane().add(stopbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        packetbtn.setText("PACKET VIEW");
        packetbtn.setFocusable(false);
        packetbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        packetbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        packetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packetbtnActionPerformed(evt);
            }
        });
        getContentPane().add(packetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        sessionbtn.setText("SESSION VIEW");
        sessionbtn.setFocusable(false);
        sessionbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sessionbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sessionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sessionbtnActionPerformed(evt);
            }
        });
        getContentPane().add(sessionbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 70));

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 150, 630));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setBorderPainted(false);

        jMenu2.setText("Configuration");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Basic Configuration");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem3.setText("Filter Cnofiguration");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void packetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packetbtnActionPerformed
        // TODO add your handling code here:
        packetView();
        stopSession();
    }//GEN-LAST:event_packetbtnActionPerformed

    private void sessionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sessionbtnActionPerformed
        // TODO add your handling code here:
        sessionView();
      //  sessionArea.setText("");
        startSession();
       // ps.startSesUpdating();
        
    }//GEN-LAST:event_sessionbtnActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        BasicConfiguration bc = new BasicConfiguration();
        bc.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void startbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbtnActionPerformed
        // TODO add your handling code here:
        startPacketbtn();
        ps.startUpdating();
    }//GEN-LAST:event_startbtnActionPerformed

    private void stopbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopbtnActionPerformed
        // TODO add your handling code here:
        stopPacketbtn();
        ps.stopUpdating();
    }//GEN-LAST:event_stopbtnActionPerformed

    private void refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed
        // TODO add your handling code here:
        sessionArea.setText("");
        ps.startSesUpdating();
    }//GEN-LAST:event_refreshbtnActionPerformed

    private void packetTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_packetTableMousePressed
        // TODO add your handling code here:
        if(packetTable.getSelectedRowCount() != 0)
        {
            int row = packetTable.getSelectedRow();
            packetArea.setText(packetTable.getValueAt(row, 11).toString());
        }
    }//GEN-LAST:event_packetTableMousePressed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        FilterSetting fs = new FilterSetting();
        fs.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        new FilterSetting().setVisible(true);
    }//GEN-LAST:event_jMenu2ActionPerformed

    void packetView()
    {
        packetView.setVisible(true);
        packetPanel.setVisible(true);
        sessionView.setVisible(false);
        sessionPanel.setVisible(false);
    }
    
    void sessionView()
    {
        sessionView.setVisible(true);
        sessionPanel.setVisible(true);
        packetView.setVisible(false);
        packetPanel.setVisible(false);
    }
    
    void startPacketbtn()
    {
        menuStatusFalse();
        startbtn.setEnabled(false);
        stopbtn.setEnabled(true);
    }
    
    void stopPacketbtn()
    {
        menuStatusTrue();
        startbtn.setEnabled(true);
        stopbtn.setEnabled(false);
    }
    
    void startSession()
    {
        menuStatusFalse();
        refreshbtn.setEnabled(true);
        
    }
    
    void stopSession()
    {
        menuStatusTrue();
        refreshbtn.setEnabled(false);
        
    }
    
    void menuStatusTrue()
    {
        jMenuItem1.setEnabled(true);
      //  jMenuItem2.setEnabled(true);
    }
    
    void menuStatusFalse()
    {
        jMenuItem1.setEnabled(false);
       // jMenuItem2.setEnabled(false);
    }
    static void deletePreviousFiles()
    {
        String dir="Filter Setting";
        String filePort=dir+"\\Port Filter.txt";
        String fileIP=dir+"\\IP Filter.txt";
        String fileWord=dir+"\\Word Filter.txt";
        File file;
        new File(filePort).delete();
        new File(fileIP).delete();
        new File(fileWord).delete();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainGUI(100,true,2).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JTextArea packetArea;
    private javax.swing.JPanel packetPanel;
    private javax.swing.JTable packetTable;
    private javax.swing.JPanel packetView;
    private javax.swing.JButton packetbtn;
    private javax.swing.JButton refreshbtn;
    public javax.swing.JTextArea sessionArea;
    private javax.swing.JPanel sessionPanel;
    private javax.swing.JPanel sessionView;
    private javax.swing.JButton sessionbtn;
    private javax.swing.JButton startbtn;
    private javax.swing.JButton stopbtn;
    // End of variables declaration//GEN-END:variables
}
