/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogFileBrowse.java
 *
 * Created on Mar 22, 2012, 8:17:00 PM
 */
package javamodules;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.StringTokenizer;

/**
 *
 * @author RAVI
 */
public class LogFileBrowse extends javax.swing.JFrame {

    /** Creates new form LogFileBrowse */
    DefaultTableModel dtm;
    public LogFileBrowse() {
        initComponents();
       resultTable.setCellSelectionEnabled(false);
       resultTable.setRowSelectionAllowed(false);
       resultTable.setColumnSelectionAllowed(false);
       dtm = (DefaultTableModel)resultTable.getModel();
       searchbtn.setMnemonic(KeyEvent.VK_ENTER);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dayText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        monthCombo = new javax.swing.JComboBox();
        yearCombo = new javax.swing.JComboBox();
        searchbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search Log File");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        jLabel1.setText("Enter Date for Log File :");

        dayText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayTextActionPerformed(evt);
            }
        });
        dayText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dayTextFocusLost(evt);
            }
        });
        dayText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dayTextKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel2.setText("Day");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel3.setText("Year");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel4.setText("Month");

        monthCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Select Month --", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthComboActionPerformed(evt);
            }
        });

        yearCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Select Year --", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));

        searchbtn.setMnemonic(KeyEvent.VK_ENTER);
        searchbtn.setText("SEARCH");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Source IP", "Destination IP", "Source Port", "Destination Port", "Source MAC", "Destination MAC", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(resultTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dayText, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1067, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(searchbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yearCombo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(dayText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static int c = 0 ;
    private void dayTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dayTextKeyTyped
        //Integer.parseInt(dayText.getText());
        if(dayText.getText().length()> 1)
        {
            dayText.setText("");
            dayText.requestFocusInWindow();
        }
    }//GEN-LAST:event_dayTextKeyTyped

    private void dayTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dayTextFocusLost
        try{
            if(Integer.parseInt(dayText.getText())> 31 )
            {
                JOptionPane.showMessageDialog(this, "Enter only valid Integers.", "ERROR", JOptionPane.PLAIN_MESSAGE);
                dayText.requestFocusInWindow();
            }
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Enter Date.", "ERROR", JOptionPane.PLAIN_MESSAGE);
            dayText.requestFocusInWindow();
        }
        
    }//GEN-LAST:event_dayTextFocusLost

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        String day = dayText.getText();
        resultTable.removeAll();
        int m = monthCombo.getSelectedIndex();
        String month;
        if(Integer.parseInt(day)< 10)
        {
            day = "0"+day;
        }
        if(m < 10)
        {
            month = "0"+m;
        }
        else
            month = ""+m;
        String year = yearCombo.getSelectedItem().toString();
        if(day.isEmpty())
            JOptionPane.showMessageDialog(this, "Enter Date.", "ERROR", JOptionPane.PLAIN_MESSAGE);
        else if(m == 0 || yearCombo.getSelectedIndex() == 0  )
        {
            JOptionPane.showMessageDialog(this, "Select month/year.", "ERROR", JOptionPane.PLAIN_MESSAGE);
        }
        else
        {
            String dir="Log Files//";
            String csvFile =dir+day + "_" + month + "_" + year + "_log_file.csv";
            System.out.println(csvFile);
            for(int i = resultTable.getRowCount()-1; i>=0; i--)
                    dtm.removeRow(i);
            try { 
                //create BufferedReader to read csv file
                BufferedReader br = new BufferedReader(new FileReader(csvFile));
                String line = "";
                StringTokenizer st = null;

                int lineNumber = 0; 
                int tokenNumber = 0;
                
                //read comma separated file line by line
                while ((line = br.readLine()) != null) {
                    lineNumber++;

                    //use comma as token separator
                    st = new StringTokenizer(line, ",");
                    String obj[]= new String[7];
                    while (st.hasMoreTokens()) {
                        
                        
                        //display csv values
                        //System.out.print(st.nextToken() + "  ");
                        obj[tokenNumber]=st.nextToken().toString();
                        tokenNumber++;
                    }
                    dtm.addRow(obj);
                    System.out.println();
                    //reset token number
                    tokenNumber = 0;
                }
            }
            catch(FileNotFoundException e)
            {
                resultTable.removeAll();
                JOptionPane.showMessageDialog(this, "No file Found.", "ERROR", JOptionPane.PLAIN_MESSAGE);
            }
            catch (Exception e) {
                System.err.println("CSV file cannot be read : " + e);
            }
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void dayTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayTextActionPerformed

    private void monthComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthComboActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dayText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox monthCombo;
    private javax.swing.JTable resultTable;
    private javax.swing.JButton searchbtn;
    private javax.swing.JComboBox yearCombo;
    // End of variables declaration//GEN-END:variables
}
